# Generated by Django 3.0.3 on 2020-03-04 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('cpf', models.CharField(max_length=15)),
                ('rg', models.CharField(max_length=15)),
                ('birth_date', models.DateField()),
                ('adress', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('salary', models.FloatField()),
                ('acess_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('cpf', models.CharField(max_length=15)),
                ('rg', models.CharField(max_length=15)),
                ('birth_date', models.DateField()),
                ('adress', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('acess_level', models.IntegerField()),
                ('payed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('conditions', models.CharField(max_length=400)),
                ('services', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('cpf', models.CharField(max_length=15)),
                ('rg', models.CharField(max_length=15)),
                ('birth_date', models.DateField()),
                ('adress', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('salary', models.FloatField()),
                ('acess_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('cpf', models.CharField(max_length=15)),
                ('rg', models.CharField(max_length=15)),
                ('birth_date', models.DateField()),
                ('adress', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('salary', models.FloatField()),
                ('acess_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled', models.DateTimeField()),
                ('observations', models.CharField(max_length=200)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('rating', models.FloatField()),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Technician')),
            ],
        ),
        migrations.CreateModel(
            name='SalesVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=40)),
                ('client_phone', models.CharField(max_length=15)),
                ('client_email', models.EmailField(max_length=254)),
                ('adress', models.CharField(max_length=80)),
                ('scheduled', models.DateTimeField()),
                ('observations', models.CharField(max_length=200)),
                ('was_sale', models.BooleanField()),
                ('rating', models.FloatField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=40)),
                ('serial_number', models.CharField(max_length=30)),
                ('potency', models.FloatField()),
                ('model', models.CharField(max_length=30)),
                ('qrcode', models.CharField(max_length=260)),
                ('pipe_amount', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Client')),
            ],
        ),
    ]
