# Generated by Django 3.0.3 on 2020-03-04 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='Product',
        ),
    ]
