# Generated by Django 3.0.3 on 2020-03-04 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200304_1509'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='Gerente',
        ),
    ]
