# Generated by Django 3.0.3 on 2020-03-04 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200304_1834'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Cliente',
        ),
        migrations.RenameModel(
            old_name='Seller',
            new_name='Gerente',
        ),
        migrations.RenameModel(
            old_name='Machine',
            new_name='Maquina',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Produto',
        ),
        migrations.RenameModel(
            old_name='Technician',
            new_name='Tecnico',
        ),
        migrations.RenameModel(
            old_name='Admin',
            new_name='Vendedor',
        ),
        migrations.RenameModel(
            old_name='TechnicalVisit',
            new_name='VisitaTecnica',
        ),
        migrations.RenameModel(
            old_name='SalesVisit',
            new_name='VisitaVenda',
        ),
        migrations.AlterModelTable(
            name='vendedor',
            table=None,
        ),
    ]
