# Generated by Django 3.0.3 on 2020-03-13 16:53

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20200304_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='install_date',
            field=models.DateTimeField(default=builtins.dir),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitavenda',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Vendedor'),
        ),
    ]
